### ISSUE TITLE
Display active environment next to menu button or Pentaho Repository Connect button

### ISSUE THREAD

**Issue by pgi-jsanchez** [mattcasters/kettle-environment#13]
This it's just a visual improvement that makes it easy to find out which environment it's active instead of displaying this inside the transformation or job. Also because when you zoom in or out, this label increases or decreases it's font size.

**Comment by mattcasters** [comment]
Yeah, except that it's pretty much impossible without changing core pentaho-kettle code which isn't going to happen any time soon.

**Comment by mattcasters** [comment]
I decreased the font size a bit, should be better now.
