### ISSUE TITLE
Need feature to import and export an environment from/to a text file.

### ISSUE THREAD

**Issue by usbrandon** [mattcasters/kettle-environment#18]
Use case: 
My copy of Kettle exists in an immutable docker container.  Environment information including everything that ends up in a .kettle folder (except for the db cache file) is configuration data and should not belong to the image.  Connection information is sensitive, and Docker has a standard way to deal with sensitive data by using 'secrets'.  If I had a way to export a configuration for each environment to a text file, I could create docker secrets for each one, and expose them to the kettle docker container when it spins up.
Docker container secrets always appear in /run/secrets/(name of the secret you chose when creating it).  The script that launches kettle could first use the 'import environment from file' feature (proposed here) to let the environment plugin get configured with details about all of the environments before kettle starts with any particular environment.

Expected benefits:
* Containers do not bake in any sensitive configuration information
* We can version the sensitive environments elsewhere as portable files in a single project instead of embedding them in every project.
* Preserve the ability to embed environments inside git versioned projects

Docker is super easy to illustrate.  I will try to recreate similar paths in k8s in other products like Redhat OpenShift and Google's Kubernetes cloud service, but in the interest of being concrete here is Docker using its built in Swarm.

Create a one node docker swarm
```
$ docker swarm init
```

Create the docker secrets (one for each environment, probabily with a standard prefix):
```
$ printf "This might be json representing the production environment for the plugin to import." | docker secret create kettle-environment-production -
$ printf "This might be json representing the testing environment for the plugin to import." | docker secret create kettle-environment-testing -
```

Introduce the secrets (environments) to the kettle container running as a service
```
docker service  create --name webspoon --secret kettle-environment-production --secret kettle-environment-testing -p 8080:8080 mattcasters/webspoon-neo4j:latest
```
See that your new distributed, replicated webspoon service is started:
```
$ docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE                               PORTS
4hz8zj19y3ss        webspoon            replicated          1/1                 mattcasters/webspoon-neo4j:latest   *:8080->8080/tcp
```
Next we will identify the actual container running that service and go inside and illustrate how each environment can be exposed to a script for the environment plugin or other helper utility to pick up on.
```
$ docker ps
CONTAINER ID        IMAGE                               COMMAND                  CREATED              STATUS              PORTS                    NAMES
c40f2f04d75e        mattcasters/webspoon-neo4j:latest   "catalina.sh run"        About a minute ago   Up About a minute   8080/tcp                 webspoon.1.4u29a2mm5zqi9nwndjf3qa39g
$ docker exec -it webspoon.1.4u29a2mm5zqi9nwndjf3qa39g bash
root@c40f2f04d75e:/usr/local/tomcat# cd /run/secrets/
root@c40f2f04d75e:/run/secrets# ls -l
total 8
-r--r--r-- 1 root root 84 Jan  2 21:06 kettle-environment-production
-r--r--r-- 1 root root 81 Jan  2 21:06 kettle-environment-testing
root@c40f2f04d75e:/run/secrets# cat kettle-environment-production 
This might be json representing the production environment for the plugin to import.
root@c40f2f04d75e:/run/secrets# cat kettle-environment-testing 
This might be json representing the testing environment for the plugin to import.
```

See more info here:
https://docs.docker.com/engine/swarm/secrets/#defining-and-using-secrets-in-compose-files

**Comment by usbrandon** [comment]
That's a good way to look at expectations in a plugin.  Specifically that a plugin should have a standard interface for the following:
* Completely export configruation data
* Completely import configuration data
* Partially export (by some sensible grain, like environment in this case)
* Partially import (an individual environment into the plugin)

These getters and setters could leave it up to the plugin to perform the duty correctly, but the interface promise to the outside world could make development, orchestration and lifecycle simpler.

**Comment by mattcasters** [comment]
I have limited the export of an Environment to the Environment itself.
Lifecycle management of the environment content, including used files, XML, metadata stores, transformations, jobs and what not, should not be simply exported as is.  We need to aim a bit higher.
