### ISSUE TITLE
Add environment in a command line.

### ISSUE THREAD

**Issue by ravamo** [mattcasters/kettle-environment#29]
Hi @mattcasters 
It would be a good idea to include the possibility of the environment through the command line like kitchen or pan.
`kitchen.sh -file=/PRD/updateWarehouse.kjb -level=Minimal -environment=Default`

**Comment by mattcasters** [comment]
Without a fork, Kitchen can't be fixed. It's why Maitre was written in mattcasters/kettle-needful-things

**Comment by ravamo** [comment]
Great Thanks  @mattcasters  !!
