### ISSUE TITLE
Could we have a binary download of the kettle-environment plugin?

### ISSUE THREAD

**Issue by dataintrigued** [mattcasters/kettle-environment#32]
Hi Matt,

Your very useful kettle-needful-things plugin has an available binary download, however this kettle-environment plugin file does not. I have not developed Java applications for over 12 years so don't have a Java/Maven environment set up. At the moment, I have a work-around by downloading your kettle-neo4j-remix bundle from your blog and grabbing the plugin from the archive (version is kettle-environment-1.7.1-SNAPSHOT.jar).

I'm writing a blog series at the moment on these two plugins, so perhaps a readily downloadable option would be a better option moving forward?

Thanks so much for these plugins, very timely and useful for the migration work I'm doing presently.

**Comment by mattcasters** [comment]
Perhaps I'm misunderstanding but you can download the plugin in the releases section of this project.
https://github.com/mattcasters/kettle-environment/releases
